apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-saml-k8s-service-deployment
  labels:
    app: auth-saml-k8s-service
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: auth-saml-k8s-service
  template:
    metadata: 
      labels:
        app: auth-saml-k8s-service
    spec:
      containers:
      - name: auth-k8s-service
        image: vittoriapac/auth-saml-service
        ports:
        - containerPort: 8443